services:
  api_gateway:
    container_name: merchant-api-gateway
    image: danielespinoza/api-gateway:v1.0.1
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AUTH_JWT_AUTHORITY=${AUTH_JWT_AUTHORITY}
      - AUTH_JWT_AUDIENCE=${AUTH_JWT_AUDIENCE}
    networks:
      - merchant-network

  inventory_service:
    container_name: merchant-inventory-service
    image: danielespinoza/inventory-service:v1.0.2
    ports:
      - "5200:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_SQL_CONNECTION=${INVENTORY_SERVICE_CONNECTION_STRING}
      - RABBITMQ_CONNECTION_STRING=${RABBITMQ_CONNECTION_STRING}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - API_GATEWAY_ROUTE=${API_GATEWAY_ROUTE}
    networks:
      - merchant-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      inventory_service_db:
        condition: service_healthy

  payment_service:
    container_name: merchant-payment-service
    image: danielespinoza/payment-service:v1.0.3
    ports:
      - "5300:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_SQL_CONNECTION=${PAYMENT_SERVICE_CONNECTION_STRING}
      - INVENTORY_SERVICE_ROUTE=${INVENTORY_SERVICE_ROUTE}
      - ORIGIN_ROUTE=${ORIGIN_ROUTE}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_FAILED_URL=${STRIPE_FAILED_URL}
      - RABBITMQ_CONNECTION_STRING=${RABBITMQ_CONNECTION_STRING}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - merchant-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      payment_service_db:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
        interval: 10s 
        timeout: 5s
        retries: 5
        start_period: 10s 

  user_service:
    container_name: merchant-user-service
    image: danielespinoza/user-service:v1.0.1
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_SQL_CONNECTION=${USER_SERVICE_CONNECTION_STRING}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - RABBITMQ_CONNECTION_STRING=${RABBITMQ_CONNECTION_STRING}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - ADMIN_PANEL_URL=${ADMIN_PANEL_URL}
    networks:
      - merchant-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      user_service_db:
        condition: service_healthy

  notification_service:
    container_name: merchant-notification-service
    image: danielespinoza/notification-service:v1.0.1
    ports:
      - "5400:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_PORT=${EMAIL_PORT}
      - RABBITMQ_CONNECTION_STRING=${RABBITMQ_CONNECTION_STRING}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - merchant-network
    depends_on:
      rabbitmq:
        condition: service_healthy