services:
  user_service_db:
    container_name: "user_service_db"
    image: postgres:latest
    restart: always
    ports:
      - "${USER_SERVICE_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DB}
    volumes:
      - user_db:/var/lib/postgresql/data
    networks:
      - merchant-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  inventory_service_db:
    container_name: "inventory_service_db"
    image: postgres:latest
    restart: always
    ports:
      - "${INVENTORY_SERVICE_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${INVENTORY_SERVICE_DB}
    volumes:
      - inventory_db:/var/lib/postgresql/data
    networks:
      - merchant-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  payment_service_db:
    container_name: "payment_service_db"
    image: postgres:latest
    restart: always
    ports:
      - "${PAYMENT_SERVICE_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PAYMENT_SERVICE_DB}
    volumes:
      - payment_db:/var/lib/postgresql/data
    networks:
      - merchant-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:4.0-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_WEB_PORT}:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - merchant-network